"""added brightness

Revision ID: 43537e4a5259
Revises: 93baaf3e4162
Create Date: 2025-05-27 03:54:33.626247

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '43537e4a5259'
down_revision = '93baaf3e4162'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('devices', schema=None) as batch_op:
        batch_op.add_column(sa.Column('brightness', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('devices', schema=None) as batch_op:
        batch_op.drop_column('brightness')

    # ### end Alembic commands ###
