"""changed jobs

Revision ID: 4ecff2d5636e
Revises: a2e414f7c5c3
Create Date: 2025-05-27 18:57:26.109441

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import sqlite

# revision identifiers, used by Alembic.
revision = '4ecff2d5636e'
down_revision = 'a2e414f7c5c3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('jobs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('job_id', sa.String(), nullable=False),
    sa.Column('device_id', sa.Integer(), nullable=False),
    sa.Column('action', sa.String(), nullable=False),
    sa.Column('params', sa.JSON(), nullable=True),
    sa.Column('run_time', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['device_id'], ['devices.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('job_id')
    )
    op.drop_table('scheduled_actions')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('scheduled_actions',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('job_id', sa.VARCHAR(), nullable=False),
    sa.Column('device_id', sa.INTEGER(), nullable=False),
    sa.Column('action', sa.VARCHAR(), nullable=False),
    sa.Column('params', sqlite.JSON(), nullable=True),
    sa.Column('run_time', sa.DATETIME(), nullable=False),
    sa.ForeignKeyConstraint(['device_id'], ['devices.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('job_id')
    )
    op.drop_table('jobs')
    # ### end Alembic commands ###
